spring:
  application:
    name: spring-eureka-feign-client

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 180
    initial-instance-info-replication-interval-seconds: 30
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30